# Generated by Django 2.1.15 on 2021-07-02 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='listItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('isDone', models.BooleanField(default=False)),
                ('list_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list.List')),
            ],
        ),
    ]
