# Generated by Django 2.1.15 on 2021-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
